# .qodome.yml
rules:
  require_approvals: true
  min_approvals: 1
  require_status_checks: true
  auto_merge: false
  block_on_draft: true

review:
  enabled: true
  ai_reviewer: true
  suggest_changes: true
  test_coverage_check: false

notifications:
  slack: true
  github_comments: true
